# Generated by Django 3.1.5 on 2021-01-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
