# Generated by Django 3.1.5 on 2021-01-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
    ]
