# Generated by Django 3.1.5 on 2021-01-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_comments_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='News',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
