# Generated by Django 3.1.5 on 2021-01-27 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_blogcomment_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
