# Generated by Django 3.1.5 on 2021-01-27 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20210127_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
