# Generated by Django 3.1.5 on 2021-01-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
    ]
