# Generated by Django 3.1.5 on 2021-01-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20210128_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
