# Generated by Django 3.1.5 on 2021-01-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_auto_20210128_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
