# Generated by Django 3.1.5 on 2021-01-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_auto_20210128_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
