# Generated by Django 3.1.5 on 2021-01-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20210128_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
