# Generated by Django 3.1.5 on 2021-01-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_auto_20210129_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttopic',
            name='subtitle',
        ),
    ]
