# Generated by Django 3.1.5 on 2021-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0033_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='posttopic',
            name='author',
            field=models.CharField(max_length=25),
        ),
    ]
