# Generated by Django 3.1.5 on 2021-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0036_auto_20210129_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(),
        ),
    ]
