# Generated by Django 3.1.5 on 2021-01-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0040_auto_20210130_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='PostTopic',
        ),
    ]
