# Generated by Django 3.1.5 on 2021-02-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0044_auto_20210201_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='text',
        ),
    ]
