# Generated by Django 3.1.5 on 2021-02-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0045_auto_20210201_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='text',
            new_name='subtitle',
        ),
    ]
