# Generated by Django 3.1.5 on 2021-02-01 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0046_auto_20210201_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('publish',)},
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='subtitle',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='created_on',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
