# Generated by Django 3.1.5 on 2021-02-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0047_auto_20210201_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='email',
        ),
    ]
